import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
  NODE_ENV: Joi.string().required(),
  PORT: Joi.number().default(5000).required(),
  BASE_URL: Joi.string().default(5000).required(),
  FRONT_BASE_URL: Joi.string().default(5000).required(),
  DB_TYPE: Joi.string().required(),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(3306).required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  GOOGLE_CLIENT_ID: Joi.string().required(),
  GOOGLE_CLIENT_SECRET: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRATION: Joi.number().required(),
  COOKIE_DOMAIN: Joi.string().required(),
  SENDING_BLUE_CLIENT_HOST: Joi.string().required(),
  SENDING_BLUE_CLIENT_USER: Joi.string().required(),
  SENDING_BLUE_CLIENT_PASSWORD: Joi.string().required(),
  SENDING_BLUE_CLIENT_TEMPLATE_DEFAULT_NAME: Joi.string().required(),
  SENDING_BLUE_CLIENT_TEMPLATE_DEFAULT_EMAIL: Joi.string().required(),
  SENDING_BLUE_CLIENT_TEMPLATE_DIR: Joi.string().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.string().required(),
  REDIS_PASSWORD: Joi.string().required(),
});
